### ISSUE TITLE
Any chance to port to Opera or Firefox?

### ISSUE THREAD

**Issue by s8321414** [bradvin/Git-Cheat-Sheet-Chrome-Extension#3]
As title says,can this extension port to Opera and Firefox? I like this extension but my main browser is Firefox...

**Comment by bradvin** [comment]
Sorry, I do not use those browsers. The base on the plugin is simple HTML and CSS, so it should not be difficult to port them over. You are more than welcome to take this code and make a FF version

**Comment by s8321414** [comment]
Oh,thanks for your response,but I am not a developer,just hope someone will do that.
